# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "0xbro"
description: "0xbro personal site and blog related to everything that surrounds ethical hacking, penetration testing, AppSec, CTFs, and other various cybersecurity stuff."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0xbro.red" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'
#url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'
logo: "/assets/images/0xbro_minimal1.png"

# User settings
username: 0xbro
email: 0xbro.sec@gmail.com
user_title: 0xbro
twitter_username: sec_0xbro
mastodon_username: '@0xbro@infosec.exchange'
#instagram_username: foo
github_username:  '0xb120'
gitlab_username:  0xbro
telegram_username: sec_0xbro
youtube_id: '@0xbro'
linkedin_public_url: mattia-brollo-b4129614b # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url

# Build settings
#theme: minima
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 5
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Aux links for the upper right navigation
aux_links:
  "Support me!":
    - "/support-me/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
#color_scheme: light
color_scheme: light-custom

# Enable copy code button
enable_copy_code_button: true

#nav_external_links:
#  - title: My notes
#    url: https://github.com/0xb120/cheatsheets_and_ctf-notes/blob/main/Dev%2C%20ICT%20%26%20Cybersec/Dev%2C%20ICT%20%26%20Cybersec.md
#    hide_icon: false # set to true to hide the external link icon - defaults to false
#  - title: Tools cheatsheets
#    url: https://github.com/0xb120/cheatsheets_and_ctf-notes/tree/main/Dev%2C%20ICT%20%26%20Cybersec/Tools
#    hide_icon: false # set to true to hide the external link icon - defaults to false

# Footer content
back_to_top: true
back_to_top_text: "↩ Back to top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  disclosures:
    permalink: "/:collection/:path/"
    output: true
  writeups:
    permalink: "/:collection/:path/"
    output: true
  cheatsheets:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:                # Define which collections are used in just-the-docs
#    pages:                    # This is the section containing all the single pages --> about.md, home.md, tags.md
#      name: Pages
    writeups:
      name: Writeups, Articles & Videos
      nav_exclude: false
      search_exclude: false
    disclosures:
      name: Disclosures
      nav_exclude: false
      search_exclude: false
    cheatsheets:
      name: Cheatsheets and notes
      nav_exclude: false
      search_exclude: false

# Collections included for feeds
feed:
  tags: true
  posts_limit: 50
  collections:
    writeups:
      path: "/feed/articles.xml"
    disclosures:
      path: "/feed/disclosures.xml"
    cheatsheets:
      path: "/feed/cheatsheets.xml"
    posts:
      path: ""

## Callouts configs
callouts_level: quiet # or loud
callouts:
  # red
  bug:
    title: Bug
    color: red
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  # yellow
  highlight:
    color: yellow
  warning:
    title: Warning
    color: yellow
  attention:
    title: Attention
    color: yellow
  # blue
  note:
    title: Note
    color: blue
  info:
    title: Info
    color: blue
  # purple
  tip:
    title: Tip
    color: purple
  hint:
    title: Hint
    color: purple
  question:
    title: Question
    color: purple
  important:
    title: Important
    color: blue
  # green
  new:
    title: New
    color: green
  done:
    title: Done
    color: green
  success:
    title: success
    color: green
  flag:
    color: green
  # grey
  tldr:
    title: tldr
    color: grey-dk
  abstract:
    title: Abstract
    color: grey-dk
  summary:
    title: Summary
    color: grey-dk
  quote:
    color: grey-lt


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"